name: Python CI
on:
    push:
        branches:
            - main
    pull_request:
jobs:
    formatting:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.2.2
            - name: Setup Python
              uses: actions/setup-python@v5.4.0
              with:
                python-version: "3.12"
            - name: Install Dependencies
              run: |
                pip install -r requirements.txt
            - name: Check Formatting
              run: |
                black --check .

    deploy:
        needs: formatting
        runs-on: ubuntu-latest

        steps:
            - name: Simulate
              run: echo "Deploying Web Application..."
